import assert from "node:assert/strict";
import { chromium } from "playwright";

const base = process.env.E2E_BASE_URL ?? "http://127.0.0.1:3011";
const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL ?? "msedge", headless: true });

try {
  const student = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await student.goto(`${base}/login/`);
  await student.getByRole("button", { name: "학생 입장 데모" }).click();
  await student.locator('[data-demo-tour="student-post"]').click();
  await student.locator('[data-demo-tour="student-apply"]').click();
  await student.locator('[data-demo-tour="student-applied"]').click();
  await student.locator('[data-demo-tour="student-chat-send"]').click();
  await student.waitForURL(url => url.searchParams.get("id") === "a13");
  await student.locator('[data-demo-tour="agreement"]').waitFor({ timeout: 30000 });
  await student.getByRole("heading", { name: "작업 계약서" }).waitFor({ timeout: 30000 });
  await student.locator('[data-demo-tour="agreement"]').click();
  const agreement = student.locator(".agreement-dialog");
  assert.match(await agreement.getByRole("textbox", { name: "작업 범위" }).inputValue(), /월계 미용실/);
  await agreement.getByRole("button", { name: "다음", exact: true }).click();
  await agreement.getByRole("button", { name: "다음", exact: true }).click();
  assert.match(await agreement.getByRole("textbox", { name: "보상 지급" }).inputValue(), /7만원/);
  await agreement.getByRole("button", { name: "다음", exact: true }).click();
  await agreement.getByRole("button", { name: "저장하고 양쪽 확인받기" }).click();
  await agreement.getByRole("button", { name: "이 버전 최종 확인" }).waitFor();
  await agreement.getByRole("button", { name: "이 버전 최종 확인" }).click();
  await agreement.getByRole("heading", { name: "우리의 계약이 확정됐어요" }).waitFor();
  await agreement.getByText("데모에서 상대방 확인을 재현해 계약서가 확정됐어요.").waitFor();
  await student.getByRole("button", { name: "계약서 닫기" }).click();
  await student.locator('[data-demo-tour="feed-item"]').waitFor();
  await student.locator('[data-demo-tour="feed-item"]').click();
  await student.locator('[data-demo-tour="portfolio-detail"]').waitFor();
  await student.locator('[data-demo-tour="portfolio-detail"]').click();
  await student.locator('[data-demo-tour="portfolio-web"]').waitFor();
  await student.locator('[data-demo-tour="portfolio-web"]').click();
  await student.getByRole("heading", { name: "이제 자유롭게 둘러보세요" }).waitFor();
  await student.locator('[data-demo-tour="student-me"]').click();
  await student.getByRole("heading", { name: "튜토리얼 완료!" }).waitFor();
  await student.getByRole("button", { name: "자유롭게 둘러보기" }).click();
  await student.getByRole("heading", { name: "튜토리얼 완료!" }).waitFor({ state: "hidden" });
  assert.equal(await student.evaluate(() => sessionStorage.getItem("wolgye-demo-enabled")), "true");
  await student.goto(`${base}/me/`);
  await student.getByRole("button", { name: "데모 종료 · 로그인 화면으로" }).click();
  await student.getByRole("button", { name: "학생 입장 데모" }).click();
  await student.locator('[data-demo-tour="student-post"]').click();
  await student.getByRole("heading", { name: "이미 지원한 공고" }).waitFor();
  await student.getByRole("button", { name: "다음", exact: true }).click();
  await student.getByRole("heading", { name: "지원 후 채팅" }).waitFor();
  await student.close();

  const partial = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await partial.goto(`${base}/login/`);
  await partial.getByRole("button", { name: "학생 입장 데모" }).click();
  await partial.evaluate(() => sessionStorage.removeItem("wolgye-demo-tour"));
  await partial.goto(`${base}/chats/room/?id=a13`);
  await partial.locator('[data-demo-tour="agreement"]').click();
  const partialAgreement = partial.locator(".agreement-dialog");
  for (let i = 0; i < 3; i++) await partialAgreement.getByRole("button", { name: "다음", exact: true }).click();
  await partialAgreement.getByRole("button", { name: "저장하고 양쪽 확인받기" }).click();
  await partialAgreement.getByRole("button", { name: "이 버전 최종 확인" }).click();
  await partialAgreement.getByRole("button", { name: "상대방 확인 대기" }).waitFor();
  await partialAgreement.getByRole("button", { name: "계약서 닫기" }).click();
  await partial.evaluate(() => sessionStorage.setItem("wolgye-demo-tour", JSON.stringify({ role: "student", step: 4 })));
  await partial.reload();
  await partial.locator('[data-demo-tour="agreement"]').click();
  await partialAgreement.getByRole("heading", { name: "우리의 계약이 확정됐어요" }).waitFor();
  await partial.close();

  const desktop = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  await desktop.goto(`${base}/login/`);
  await desktop.getByRole("button", { name: "학생 입장 데모" }).click();
  await desktop.waitForFunction(() => document.body.classList.contains("guided-demo"));
  const phone = await desktop.locator(".app-shell").boundingBox();
  assert.ok(phone && Math.abs(phone.width - 390) < 2 && Math.abs(phone.height - 844) < 2, `데스크톱 데모가 390×844 휴대폰 크기여야 합니다: ${JSON.stringify(phone)}`);
  await desktop.evaluate(() => sessionStorage.setItem("wolgye-demo-tour", JSON.stringify({ role: "student", step: 7 })));
  await desktop.goto(`${base}/portfolio/view/?id=demo-menu-2&s=s1`);
  await desktop.locator('[data-demo-tour="portfolio-web"]').click();
  await desktop.locator('[data-demo-tour="student-me"]').waitFor();
  assert.equal(await desktop.locator('[data-demo-tour="student-me"]').isVisible(), true);
  await desktop.locator('[data-demo-tour="student-me"]').click();
  await desktop.getByRole("heading", { name: "튜토리얼 완료!" }).waitFor();
  await desktop.close();

  const merchant = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const remoteWrites = [];
  merchant.on("request", request => {
    if (/supabase\.co\/(rest|functions)\/v1/.test(request.url()) && !["GET", "HEAD"].includes(request.method())) remoteWrites.push(request.url());
  });
  await merchant.goto(`${base}/login/`);
  await merchant.getByRole("button", { name: "상인 입장 데모" }).click();
  await merchant.locator('[data-demo-tour="post-example"]').waitFor({ timeout: 30000 });
  await merchant.locator('[data-demo-tour="post-example"]').click();
  await merchant.locator('[data-demo-tour="post-submit"]').waitFor();
  await merchant.locator('[data-demo-tour="post-submit"]').click();
  await merchant.waitForURL(url => /\/posts\/detail\/?$/.test(url.pathname));
  await merchant.getByRole("heading", { name: "공고 등록 완료" }).waitFor();
  await merchant.getByRole("button", { name: "다음", exact: true }).click();
  await merchant.getByRole("heading", { name: "지원자 비교" }).waitFor();
  await merchant.getByRole("heading", { name: "지원자 2명" }).waitFor();
  await merchant.getByRole("button", { name: "다음", exact: true }).click();
  await merchant.locator('[data-demo-tour="merchant-select"]').click();
  await merchant.waitForURL(url => url.pathname.includes("/chats/room"));
  await merchant.getByText("매칭 대기", { exact: true }).waitFor();
  await merchant.locator('[data-demo-tour="agreement"]').click();
  const merchantAgreement = merchant.locator(".agreement-dialog");
  assert.match(await merchantAgreement.getByRole("textbox", { name: "작업 범위" }).inputValue(), /A3 포스터/);
  await merchantAgreement.getByRole("button", { name: "다음", exact: true }).click();
  await merchantAgreement.getByRole("button", { name: "다음", exact: true }).click();
  assert.match(await merchantAgreement.getByRole("textbox", { name: "보상 지급" }).inputValue(), /커트 1회/);
  await merchantAgreement.getByRole("button", { name: "다음", exact: true }).click();
  await merchantAgreement.getByRole("button", { name: "저장하고 양쪽 확인받기" }).click();
  await merchantAgreement.getByRole("button", { name: "이 버전 최종 확인" }).click();
  await merchantAgreement.getByRole("heading", { name: "우리의 계약이 확정됐어요" }).waitFor();
  await merchantAgreement.getByText("데모에서 상대방 확인을 재현해 계약서가 확정됐어요.").waitFor();
  await merchantAgreement.getByRole("button", { name: "계약서 닫기" }).click();
  await merchant.getByRole("heading", { name: "상인 흐름 완료" }).waitFor();
  await merchant.getByRole("button", { name: "완료", exact: true }).click();
  await merchant.getByRole("heading", { name: "상인 흐름 완료" }).waitFor({ state: "hidden" });
  assert.deepEqual(remoteWrites, []);
  await merchant.close();
  console.log("학생·상인 데모 로그인 및 안내 흐름 통과");
} finally {
  await browser.close();
}
